### ISSUE TITLE
Detach synthetic data for both D and B/H updating

### ISSUE THREAD

**Issue by pengsongyou** [jason718/game-feature-learning#3]
First of all, thanks so much for your amazing work!

I have a question on how you detach synthetic features. Detaching the synthetic feature during the update of D makes sense to me, but In [this line](https://github.com/jason718/game-feature-learning/blob/aeae123fa2876bbb42e799d4e3b4be681a769072/src/model.py#L160), you detach the synthetic feature during updating the B and H. If you do so, then network B will not be able to learn domain-invariant features because the weights won't be able to be backproped to B because of detaching.

Just curious about your explanation. 

Thanks so much for your help in advance.

**Comment by jason718** [comment]
@pengsongyou  yes, you are absolutely correct. this is a bug and I fixed it. 

Thanks very much for reading carefully and kindly pointing out. 

Note that: I re-wrote my code for public release. There is no such issue in my old code.

![Screenshot from 2019-04-15 23-03-13](https://user-images.githubusercontent.com/3235510/56181498-60e6fe00-5fd3-11e9-873d-08ab1a4db61e.png)
